// Generated by the Maven Archetype Plug-in
package vermilingua.maven.app;

import java.io.Serializable;

public class Session implements Serializable {
	private static final long serialVersionUID = 1L;

	public Session() {
		super();
	}
}
