// Generated by the Maven Archetype Plug-in
package vermilingua.maven.app;

import vermilingua.maven.components.Main;

public class DirectAction {
	private int i;

	public DirectAction(int i) {
		this.i = i;
	}
}
