// Generated by the Maven Archetype Plug-in
package ng.maven.components;

import java.io.Serializable;

public class Main implements Serializable {
	private static final long serialVersionUID = 1L;

	public Main() {
	}
}
